version: '3'

services :
  api:
    image: conference/api
    container_name: conference_api
    build:
     context: ../ConferenceApp/ConferenceApp/
     dockerfile: Dockerfile
    ports:
    - 5000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Production
   
  