apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: confapi
spec:
 replicas: 1 
 template:  
  metadata:
   labels:
    app: confapi
  spec:
   containers:
    - name: conferenceapi
      image: "dineshtripathi/conference_api:first_push"
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
      livenessProbe:
       httpGet:
        path: /api
        port: 80
      readinessProbe:
       httpGet:
        path: /api
        port: 80
     